version: '3'

services:
  hlds:
    container_name: cs-dedicated-server
    image: febley/counter-strike_server:latest
    restart: always
    privileged: true
    environment:
      - PORT=27016
      - MAP=de_dust2
      - MAXPLAYERS=16
      - SV_LAN=0
    ports:
      - 27016:27016/udp
      - 27016:27016
    volumes:
      - ./server.cfg:/hlds/cstrike/server.cfg
      - ./warmup.cfg:/hlds/cstrike/warmup.cfg
      - ./lo3.cfg:/hlds/cstrike/lo3.cfg

